POST http://localhost:3000/api/v1/urls
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InZmWVJuVkMyL1dnT3NvZXIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3d4cXppaWJnbG15Z3pza21rYm9pLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJmZTdiNDg2NC1jMmVjLTRiNGItYTVjYS04MjBjMzcwZjkwZWMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU4NDIyOTM2LCJpYXQiOjE3NTg0MTkzMzYsImVtYWlsIjoiZWRzb25sYnBldHJ5QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJlZHNvbmxicGV0cnlAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiZmU3YjQ4NjQtYzJlYy00YjRiLWE1Y2EtODIwYzM3MGY5MGVjIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NTg0MTkzMzZ9XSwic2Vzc2lvbl9pZCI6Ijk5OGI2M2IwLTA4YjQtNDZiYy04ZDQ5LWQ2MzgwODZjOTU0YSIsImlzX2Fub255bW91cyI6ZmFsc2V9.26viqsdgDZ1sSbQzpTFatoRbJz2W5ZZVS_mojYNRprE
Content-Type: application/json

{
    "url": "https://www.youtube.com"
}