GET http://localhost:3000/api/v1/urls/test-protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InZmWVJuVkMyL1dnT3NvZXIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3d4cXppaWJnbG15Z3pza21rYm9pLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJmZTdiNDg2NC1jMmVjLTRiNGItYTVjYS04MjBjMzcwZjkwZWMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU2MzQ5OTQxLCJpYXQiOjE3NTYzNDYzNDEsImVtYWlsIjoiZWRzb25sYnBldHJ5QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJlZHNvbmxicGV0cnlAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiZmU3YjQ4NjQtYzJlYy00YjRiLWE1Y2EtODIwYzM3MGY5MGVjIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NTYzNDYzNDF9XSwic2Vzc2lvbl9pZCI6IjA1ZmEzYTVjLTEzNWYtNDM1NC04NTA4LTc0M2EyODMwNGIzYyIsImlzX2Fub255bW91cyI6ZmFsc2V9.SXVfOkYCATM48Mfuo0y6vsLcQ_3zqwK9sVPnb_o6g1s