

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."url_checks" (
    "id" bigint NOT NULL,
    "checked_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "status_code" integer NOT NULL,
    "status_text" "text" DEFAULT 'NOT NULL'::"text" NOT NULL,
    "response_time_ms" integer NOT NULL,
    "url_id" "uuid" DEFAULT "gen_random_uuid"()
);


ALTER TABLE "public"."url_checks" OWNER TO "postgres";


COMMENT ON TABLE "public"."url_checks" IS 'Stores the result of every single health check.';



ALTER TABLE "public"."url_checks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."url_checks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."urls" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "url" "text" DEFAULT 'NOT NULL'::"text",
    "name" "text" DEFAULT 'NULL'::"text",
    "user_id" "uuid" DEFAULT "auth"."uid"()
);


ALTER TABLE "public"."urls" OWNER TO "postgres";


COMMENT ON TABLE "public"."urls" IS 'Stores URLs monitored by users.';



ALTER TABLE "public"."urls" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."urls_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."url_checks"
    ADD CONSTRAINT "url_checks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."urls"
    ADD CONSTRAINT "urls_pkey" PRIMARY KEY ("id");



ALTER TABLE "public"."url_checks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."urls" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."url_checks";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."url_checks" TO "anon";
GRANT ALL ON TABLE "public"."url_checks" TO "authenticated";
GRANT ALL ON TABLE "public"."url_checks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."url_checks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."url_checks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."url_checks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."urls" TO "anon";
GRANT ALL ON TABLE "public"."urls" TO "authenticated";
GRANT ALL ON TABLE "public"."urls" TO "service_role";



GRANT ALL ON SEQUENCE "public"."urls_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."urls_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."urls_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;
